[build]
  command = "npm run build"
  publish = "dist/DashBordPuzzlers/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/builders/render"
  status = 200
