[build]
  command = "npm run build"
  publish = "dist/DashBordPuzzlers/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# Proxy API requests to your backend
[[redirects]]
  from = "/api/*"
  to = "http://20.199.64.218:5000/api/:splat"
  status = 200
  force = true
